name: Resourcepack Zipper

# Only trigger on new tag pushes
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Create ZIP file
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        ZIP_NAME="hermitcraft-models-warfare-extended-${{ github.ref_name }}-${COMMIT_ID}.zip"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -qr "${ZIP_NAME}" . --exclude .env ./.github/\* ./.git/\*
        cp -l "${ZIP_NAME}" "latest.zip"
        SHA1_HASH=$(sha1sum "${ZIP_NAME}" | cut -d' ' -f1)
        echo "SHA1_HASH=${SHA1_HASH}" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ env.ZIP_NAME }}
          latest.zip
        generate_release_notes: true
        body: |
          Add these lines to `server.properties`
          ```
          resource-pack=https://github.com/jack-mil/minecraft-server-resource-pack/releases/latest/download/latest.zip
          resource-pack-sha1=${{ env.SHA1_HASH }}
          ```
